Vagrant.configure("2") do |config|
    config.vm.box     = "squeeze64puppet3"
    config.vm.box_url = "http://l4bs.slynett.com/vagrant/squeeze64-puppet3.box"

    config.vm.provider :virtualbox do |vb|
      vb.customize [
        'modifyvm', :id,
        '--name', 'develphp',
        '--memory', '512',
        '--cpus', '1'
      ]
    end

    config.vm.network :private_network, ip: '192.168.33.10'
    config.vm.hostname = "dev-lamp"

    #config.vm.synced_folder "vagrant", "/vagrant", "."
    config.vm.synced_folder "/home/belano/code/jewelry_shop", "/var/www/jewelry_shop/"

    config.vm.provision :shell, :inline => "echo \"Europe/Madrid\" | sudo tee /etc/timezone && dpkg-reconfigure --frontend noninteractive tzdata"

    config.vm.provision :puppet do |puppet|
        puppet.options = '--verbose --debug'
        puppet.manifests_path = "manifests"
        puppet.module_path    = "modules"
        #puppet.manifest_file  = "base.pp"
    end
end