## virtualhost files
shared_folder = "../../jewelry_shop"


Vagrant.configure("2") do |config|
    config.vm.box     = "squeeze64puppet3"
    config.vm.box_url = "http://l4bs.slynett.com/vagrant/squeeze64-puppet3.box"

    config.vm.provider :virtualbox do |vb|
      vb.customize [
        'modifyvm', :id,
        '--name', 'develphp',
        '--memory', '512',
        '--cpus', '1'
      ]
    end

    config.vm.network :private_network, ip: '192.168.33.10'
    config.vm.hostname = "dev-lamp"

    config.vm.synced_folder "#{shared_folder}", "/var/www/vhost/"

    config.vm.provision :puppet do |puppet|
        puppet.options = '--verbose'
        puppet.manifests_path = "manifests"
        puppet.module_path    = "modules"
        #puppet.manifest_file  = "base.pp"
    end
end